apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-on-pvc-clone-from-restored-snap
  name: pod-on-pvc-clone-from-restored-snap
  namespace: $ANOTHER_NAMESPACE
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Always  
  containers:
  - image: alpine:3.7
    name: pod-on-pvc-clone-from-restored-snap
    resources: {}
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-clone-from-restored-snap
status: {}