kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: original-pvc
   namespace: $NAMESPACE
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi
   storageClassName: $STORAGE_CLASS