apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snap-original-pvc
  namespace: $NAMESPACE
spec:
  volumeSnapshotClassName: $VOLUME_SNAPSHOT_CLASS
  source:
    persistentVolumeClaimName: original-pvc