apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-on-pvc-clone-from-snap-original-pvc
  name: pod-on-pvc-clone-from-snap-original-pvc
  namespace: $NAMESPACE
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  containers:
  - image: alpine:3.7
    name: pod-on-pvc-clone-from-snap-original-pvc
    securityContext: 
      allowPrivilegeEscalation: false
      capabilities: 
        drop: 
        - "ALL"
      runAsNonRoot: true 
      seccompProfile: 
        type: "RuntimeDefault" 
    resources: {}
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-clone-from-snap-original-pvc
status: {}